name: First Action Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye!!"
  second-job:
    runs-on: macos-13
    steps:
      - name: Print Greeting in mac
        run: echo "Hello world in MAC!"
      - name: Print goodbye
        run: echo "Done - bye in MAC!!"
    
